### ISSUE TITLE
After a while Nuimo lib reaches D-Bus connection limits

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/nuimo-hub-backend#65]
We probably don't release some connections that we opened

```
2017-03-14 15:02:02,652 ERROR [dbus.connection] Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/srv/nuimo_hub/venv/lib/python3.4/site-packages/gatt/gatt_linux.py", line 141, in _interfaces_added
    self._device_discovered(path, interfaces)
  File "/srv/nuimo_hub/venv/lib/python3.4/site-packages/gatt/gatt_linux.py", line 155, in _device_discovered
    device = self.make_device(mac_address)
  File "/srv/nuimo_hub/venv/lib/python3.4/site-packages/nuimo/nuimo.py", line 38, in make_device
    device = super().make_device(mac_address)
  File "/srv/nuimo_hub/venv/lib/python3.4/site-packages/gatt/gatt_linux.py", line 177, in make_device
    return Device(adapter_name=self.adapter_name, mac_address=mac_address)
  File "/srv/nuimo_hub/venv/lib/python3.4/site-packages/gatt/gatt_linux.py", line 219, in __init__
    self.properties_signal_match = self.properties.connect_to_signal('PropertiesChanged', self.properties_changed)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 544, in connect_to_signal
    dbus_interface, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 369, in connect_to_signal
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 157, in add_signal_receiver
    watch = self.watch_name_owner(bus_name, callback)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 373, in watch_name_owner
    return NameOwnerWatch(self, bus_name, callback)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 80, in __init__
    arg0=bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 160, in add_signal_receiver
    self.add_match_string(str(match))
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 398, in add_match_string
    BUS_DAEMON_IFACE, 'AddMatch', 's', (rule,))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.LimitsExceeded: Connection ":1.19" is not allowed to add more match rules (increase limits in configuration file if required)
```

**Comment by larsblumberg** [comment]
This is fixed now when the glib's run loop is started by means of the Nuimo SDK. As soon as the loop stops, Nuimo SDK remove all connected signals.
